{
	"Name":"Samantha",
	"Set":{
		"MysteryBox":{
			"Laugh":[
				"nzu/mysterybox/disappear_flux.wav"
			],
			"Leave":[
				"nzu/announcer/samantha/byebye.wav"
			]
		},
		"Round":{
			"SpecialStart":[
				"nzu/announcer/samantha/dogstart.wav"
			]
		},
		"Powerups":{
			"MaxAmmo":[
				"nzu/announcer/samantha/powerups/maxammo.wav"
			],
			"Carpenter":[
				"nzu/announcer/samantha/powerups/carpenter.wav"
			],
			"DoublePoints":[
				"nzu/announcer/samantha/powerups/doublepoints.wav"
			],
			"Nuke":[
				"nzu/announcer/samantha/powerups/nuke.wav"
			],
			"InstaKill":[
				"nzu/announcer/samantha/powerups/instakill.wav"
			],
			"FireSale":[
				"nzu/announcer/samantha/powerups/firesale.wav"
			]
		}
	}
}